name: Build Android Release

on:
  workflow_dispatch: # Manual trigger
  push:
    tags:
      - "v*" # Trigger on tags like v1.0.0

jobs:
  build-android:
    runs-on: ubuntu-latest

    env:
      JAVA_HOME_17_X64: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.16-8/x64
      ANDROID_KEYSTORE_BASE64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
      ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
      ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
      ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}

    steps:
      # 1️⃣ Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v5

      # 2️⃣ Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 20

      # 3️⃣ Cache node_modules
      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # 4️⃣ Install npm dependencies
      - name: Install npm dependencies
        run: npm install

      # 5️⃣ Build web assets
      - name: Build frontend
        run: npm run build

      # 6️⃣ Sync Capacitor Android
      - name: Sync Capacitor Android
        run: npx cap sync android

      # 7️⃣ Setup JDK 17
      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # 8️⃣ Cache Gradle
      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper/
          key: ${{ runner.os }}-gradle-${{ hashFiles('android/gradle/wrapper/gradle-wrapper.properties') }}

      # 9️⃣ Decode Keystore
      - name: Decode Keystore
        run: |
          mkdir -p android/app
          echo "$ANDROID_KEYSTORE_BASE64" | base64 --decode > android/app/release.keystore

      # 🔟 Ensure Gradle uses Java 17
      - name: Set Gradle JDK
        run: echo "org.gradle.java.home=$JAVA_HOME_17_X64" >> android/gradle.properties

      # 1️⃣1️⃣ Build signed release APK
      - name: Build Android Release APK
        working-directory: android
        run: |
          ./gradlew clean
          ./gradlew assembleRelease \
            -Pandroid.injected.signing.store.file=app/release.keystore \
            -Pandroid.injected.signing.store.password=$ANDROID_KEYSTORE_PASSWORD \
            -Pandroid.injected.signing.key.alias=$ANDROID_KEY_ALIAS \
            -Pandroid.injected.signing.key.password=$ANDROID_KEY_PASSWORD \
            -Dorg.gradle.java.home=$JAVA_HOME_17_X64

      # 1️⃣2️⃣ Upload APK artifact
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-release-apk
          path: android/app/build/outputs/apk/release/app-release.apk

      # 1️⃣3️⃣ Create GitHub Release
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: android/app/build/outputs/apk/release/app-release.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
